language: php

php:
  - 5.3
  - 5.4
  - 5.5
#  - 5.6

before_script:
  - composer install --prefer-source
  - phpenv rehash

script:
  - phpunit --coverage-text
  - ./vendor/bin/phpcs --standard=./phpcs.xml -n --report=gitblame --ignore=src/DateTimeCompat src/
